name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Extract version
            id: extract-version
            run: echo "version=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
     
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . ghcr.io/forscht/ddrive:${{ steps.extract-version.outputs.version }}
              docker push ghcr.io/forscht/ddrive:${{ steps.extract-version.outputs.version }}